### ISSUE TITLE
Simulated orientation sensors run slow

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub_simulator#104]
Although the rate for the bno055_left sensor is set to 20hz, it actually publishes at a rate of 5hz. After much debugging, @ryan-summers and myself discovered it's due to latency of the bno055 making several serial requests to the simulator_bridge node. Speeding up the rate of the simulator_bridge node reduces the latency, but this problem will always exist.

After some deliberation, we propose that the bno055 emulator be eliminated, and just have the simulator_bridge publish orientation data to its own topic that the imu node then forwards.

**Comment by ryan-summers** [comment]
Closed as of https://github.com/PalouseRobosub/robosub_simulator/pull/113
