### ISSUE TITLE
Thruster Timeout

### ISSUE THREAD

**Issue by dcrossman** [PalouseRobosub/robosub_simulator#11]
The real thrusters, if they have not received a command in some amount of time (I'm not sure what it actually is), will timeout and stop spinning. This should be implemented in the thruster plugin.

**Comment by dcrossman** [comment]
@irwineffect do you know how long the actual thruster timeout is?

**Comment by irwineffect** [comment]
Nah I don't. @ryan-summers, do you know?

**Comment by ryan-summers** [comment]
From the[ Maestro manual](https://www.pololu.com/docs/0J40/all#5.a):

>**Timeout**: This parameter specifies the duration before which a Serial timeout error will occur. This error can be used as a safety measure to ensure that your servos and digital outputs go back to their default states whenever the software sending commands to the Maestro stops working. The serial timeout error will occur whenever no valid serial commands (or qualifying native USB commands) are received within the specified timeout period. A timeout period of 0.00 disables the serial timeout error. The resolution of this parameter is 0.01 s and the maximum value available is 655.35 s. The native USB commands that qualify correspond to the following methods in the Usc class: setTarget, setSpeed, setAcceleration, setPwm, disablePWM, and clearErrors. Running the Maestro Control Center will not prevent the serial timeout error from occurring, but setting targets in the Status tab or playing a sequence will.

Therefore, the timeout is whatever we set it to be. I do not believe it has currently been set.

**Comment by irwineffect** [comment]
How does a value of 1 or 0.5 seconds sound?

**Comment by ryan-summers** [comment]
0.5 is good

**Comment by dcrossman** [comment]
See #21
