### ISSUE TITLE
Dice are not being displayed properly.

### ISSUE THREAD

**Issue by Sindorman** [PalouseRobosub/robosub_simulator#119]
Me and Lance have noticed that Dice are not being loaded fully. Here is an image of what they look like.
simulator branch is `master`.
![bug_simulator](https://user-images.githubusercontent.com/25555314/35655818-b3b00738-06a8-11e8-9315-63c2a26f1f8b.png)

**Comment by ryan-summers** [comment]
@irwineffect I think we need to add Git LFS as a dependency of the robosub packages to ensure that people have it installed on their system. I think the effect shown is because the JPEG textures aren't getting pulled down because LFS isn't installed on the target machine.

**Comment by ryan-summers** [comment]
I _believe_ this should be corrected by typing `git lfs install` in the simulator repository and then pulling master.

**Comment by neprotalis** [comment]
This is correct. I talked with Sean about it and he is going to show me how to add it to the repo. It will be corrected soon. If you need it now though https://github.com/git-lfs/git-lfs/wiki/Installation

**Comment by ryan-summers** [comment]
After LFS is installed, type `git lfs pull` to pull down the JPEG textures.

**Comment by hmmwhatsthisdo** [comment]
@ryan-summers `git lfs install` only works once the `git-lfs` package is added, unfortunately.

**Comment by ryan-summers** [comment]
We're adding it to robosub package dependencies.
