### ISSUE TITLE
Simulated Vision Network does not fill out Timestamp

### ISSUE THREAD

**Issue by ryan-summers** [PalouseRobosub/robosub_simulator#122]
Because the header isn't properly completed, the DetectionArray message cannot be used by ApproximateTimeSynchronizer classes.

**Comment by neprotalis** [comment]
The header for the message is fine, we just need to timestamp before publishing the detection_msg.
detections_msg.header.stamp = rospy.Time.now() fixes the issue.

**Comment by ryan-summers** [comment]
This was merged in #125
