### ISSUE TITLE
Gibb Pool World

### ISSUE THREAD

**Issue by dcrossman** [PalouseRobosub/robosub_simulator#30]
Title says it all.

**Comment by dcrossman** [comment]
Does anyone know the exact dimensions of the gibb pool btw?

**Comment by bkallaher** [comment]
The lap section is 25 yards long with 8 lanes each at 6 ft each. So 25 yards by 48 ft. I think it starts at 4-4.5 ft deep and progresses down to 8ish ft. The dive section is 14 ft deep no clue on other dimensions.

**Comment by dcrossman** [comment]
Measure during 1/22 pool test!

**Comment by bkallaher** [comment]
Solidworks model created. Need to export to stl or dae somehow.

**Comment by irwineffect** [comment]
fixed by #60
