### ISSUE TITLE
Add thruster deadzones

### ISSUE THREAD

**Issue by dcrossman** [PalouseRobosub/robosub_simulator#53]

**Comment by ryan-summers** [comment]
Please expand this to map received signals to thruster forces as specified on [BlueRobotics T200 Documentation](http://docs.bluerobotics.com/thrusters/t200/) through polynomial curve fitting.

**Comment by ryan-summers** [comment]
Pull request: https://github.com/PalouseRobosub/robosub_simulator/pull/59

**Comment by irwineffect** [comment]
fixed by #59
