### ISSUE TITLE
Fix weird camera distortions in simulated vision

### ISSUE THREAD

**Issue by dcrossman** [PalouseRobosub/robosub_simulator#65]
![gazebodistortions](https://cloud.githubusercontent.com/assets/4917927/23044620/deda5762-f455-11e6-90d2-b1b5b7270a52.png)

**Comment by bkallaher** [comment]
These are artifacts from the cube mapping. No fix known.

**Comment by irwineffect** [comment]
I think the fix is to get UWsim working.

**Comment by skallaher** [comment]
Would UWSim use a different sensor model? If not, this would still exist. It's a part of the wide-angle camera sensor.

**Comment by ryan-summers** [comment]
Yeah, I don't think there's much we can do about this as it appears to be a result of how Gazebo works with cameras.
