### ISSUE TITLE
Simple Mesh to SDF conversion

### ISSUE THREAD

**Issue by bkallaher** [PalouseRobosub/robosub_simulator#7]
The collada files for things like the buoys and the gate should be converted to SDF. This should be relatively simple as the models are just cylinders and spheres.

**Comment by bkallaher** [comment]
@BigDCross: Buoys converted.

**Comment by bkallaher** [comment]
![newvsoldbuoys](https://cloud.githubusercontent.com/assets/7076181/21245215/334eacaa-c2d6-11e6-87c9-6b3e5ce0fc5c.png)

Old is on the right and new is on the left.

**Comment by skallaher** [comment]
Why does the yellow buoy look white?

**Comment by bkallaher** [comment]
That is the old one. I don't know why.

**Comment by skallaher** [comment]
Ah, I just got them backwards. Is there an easy way to make them less neon?

**Comment by bkallaher** [comment]
Right now I'm just using the gazebo default colors for red, green, and yellow. I'll mess around with the diffusion, emissive, specular, and ambient values a bit to remove some of the "life" from the colors.

**Comment by bkallaher** [comment]
Or find a shader map that will do the trick.
