### ISSUE TITLE
Add fisheye distortion to Camera Sensors

### ISSUE THREAD

**Issue by ryan-summers** [PalouseRobosub/robosub_simulator#80]
We need to test our vision system with fisheye distortion and non-ideal lenses. Attempt to implement a fisheye model of distortion to the simulated cameras comparable to what we see on our current cameras.

**Comment by skallaher** [comment]
This has already been done using data gathered from the camera calibration. Please note #16 and #49.

**Comment by ryan-summers** [comment]
To my knowledge, the fishy appears incorrect. Modifying distortion parameters in the sdf does not change the image outputs

**Comment by skallaher** [comment]
Modifying the SDF does, in fact, change the image, though minor changes may not make a huge impact. How does it appear incorrect?
