### ISSUE TITLE
Modify Image Publishing to output WFOVImage messages on correct topics

### ISSUE THREAD

**Issue by skallaher** [PalouseRobosub/robosub_simulator#81]
Change the simulator to publish a WFOVImage rather than an Image to imitate the pointgrey camera drivers. 
Change topics published to for these images to be **/camera/{left|right|bottom}/image** rather than **/camera/{left|right|bottom}** to replicate pointgrey camera drivers.

**Comment by irwineffect** [comment]
Note that if we complete PalouseRobosub/robosub#221, then there is no need to have the simulator publish WFOV. Publishing a normal image instead of WFOV image is the most desired behavior.

**Comment by skallaher** [comment]
Looking at the sdf, it would be much easier if the cameras published a standard image as making the simulator publish a WFOV would involve messing with the gazebo_ros_camera library.

**Comment by skallaher** [comment]
This is not needed after #93 and PalouseRobosub/robosub#246 are merged.

**Comment by skallaher** [comment]
Fixed via PalouseRobosub/robosub#246.
